[build]
  publish = "."

[build.environment]
  GIT_LFS_ENABLED = "true"
  GIT_LFS_FETCH_INCLUDE = "*.mp4"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "video/mp4"

[[headers]]
  for = "/assets/ca-khuc/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "video/mp4"
